import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/Provider";
import LayoutShell from "@/components/layout/LayoutShell";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full">
        <ReduxProvider>

       <LayoutShell>
         {children}
       </LayoutShell>
        
        </ReduxProvider>
        
        </body>
    </html>
  );
}
